# Generated by Django 6.0.1 on 2026-02-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='Description',
            new_name='CategoryDescription',
        ),
    ]
