# Generated by Django 6.0.1 on 2026-02-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_rename_description_categorydb_categorydescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, unique=True)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductDescription', models.TextField()),
                ('ProductImage', models.ImageField(upload_to='products')),
            ],
        ),
    ]
