# Generated by Django 6.0.1 on 2026-02-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='ProductName',
            new_name='Category_Name',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='ProductDescription',
            new_name='Product_Description',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='ProductImage',
            new_name='Product_Image',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='CategoryName',
            new_name='Product_Name',
        ),
    ]
