# Generated by Django 6.0.1 on 2026-02-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_productname_productdb_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Product_Price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
