# Generated by Django 6.0.1 on 2026-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_servicedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedb',
            name='ServiceImage',
            field=models.ImageField(upload_to='services'),
        ),
    ]
