# Generated by Django 6.0.2 on 2026-02-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Cart_ProductImage',
            field=models.ImageField(blank=True, null=True, upload_to='Cart_Image'),
        ),
    ]
