# Generated by Django 6.0.2 on 2026-03-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_orderdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Blog_Description', models.TextField(blank=True, null=True)),
                ('Blog_Image', models.ImageField(blank=True, null=True, upload_to='Blog_Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
